# Generated by Django 5.0.6 on 2024-12-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aid',
            field=models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
