# Generated by Django 5.0.6 on 2024-12-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_aid_delete_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aid',
            field=models.ForeignKey(db_column='aid', default='null', on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
    ]
