# Generated by Django 5.0.6 on 2024-12-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_order_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aid',
            field=models.ForeignKey(db_column='aid', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
    ]
