# Generated by Django 5.0.6 on 2024-12-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_deliverystatus_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='oid',
            field=models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='myapp.order'),
        ),
    ]
